Models/ErrorViewModel.cs
using System;

namespace Tutorial.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System;
using System.Text;
using System.ComponentModel.DataAnnotations;  
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography;


namespace Tutorial.Models
{
    public class User 
    {
        [Key, Column(Order = 1)]  
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)] 
        public int ID{get;set;}
        public string Firstrname{get;set;}

        public string Lastname {get;set;}
        [DataType(DataType.Date)]
        public DateTime? Date_birth{get;set;}

        [Required]
        public string Email {get;set;}
        [Required]
        public string Password {get;set;}

        public void SetPassword(string value)
        {
            Password = HashPasword(value);
        }
        public static string HashPasword(string value)
        {
            string res="";
            SHA256 shcrypt = SHA256.Create();
            byte[] hash = shcrypt.ComputeHash(Encoding.UTF8.GetBytes(value));
            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < hash.Length; i++)
            {
                builder.Append(hash[i].ToString());
            }
            res = builder.ToString();
            return res;
        }
    }
}

ViewModels/LoginVModel.cs
using System.ComponentModel.DataAnnotations;
namespace Tutorial.ViewModels
{
    public class LoginVModel
    {   
        [Required (AllowEmptyStrings= false , ErrorMessage="L'email est requis")]
        [EmailAddress(ErrorMessage = "Adresse non valide")]
        [Display(Name="Adresse Email")]
        public string Email {get;set;}

        [DataType(DataType.Password)]
        [Required(ErrorMessage="Veuillez saisir un mot de passe")]
        [Display(Name="Mot de passe")]
        public string Password {get;set;}
        
    }
}

ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Tutorial.ViewModels
{
    public class RegisterViewModel
    {
        [Required (AllowEmptyStrings = false, ErrorMessage = "L'email est requis")]
        [EmailAddress(ErrorMessage = "Adresse non valide")]
        [Display(Name = "E-mail")]
        public string Email {get;set;}
        
        [RegularExpression("(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9]).{7,}$",ErrorMessage = "Chiffre + Majuscules requis")]
        [StringLength(20, MinimumLength = 7,  ErrorMessage = "Minimum 7 caractères")]
        [DataType(DataType.Password)]
        [Required (AllowEmptyStrings = false, ErrorMessage = "Le mot de passe est requis")]
        [Display(Name = "mot de passe")]
        public string Password{get;set;}
        [DataType(DataType.Password)]
        [Required (AllowEmptyStrings = false, ErrorMessage = "Confirmez le mot de passe")]
        [Compare("Password", ErrorMessage = "Les mots de passe ne correspondent pas !")]
        [Display(Name = "Confirmez")]
        public string Pass_confirm{get;set;}
        
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

using Tutorial.ViewModels;
using Tutorial.Models;
using Tutorial.Data;




namespace Tutorial.Controllers
{
    [Route("auth")]
    public class AuthController : Controller
    {

        private readonly  UserContext _context;
        public AuthController(ILogger<AuthController> logger, UserContext context )
        {
            _context = context;
            this.logger = logger;
        }

        private ILogger logger ;
        
        
        [HttpGet]
        [Route("register")]
        public IActionResult Register()
        {

            return View();
        }

        [HttpPost]
        [Route("register")]
        [ValidateAntiForgeryToken]
        public ActionResult Register( RegisterViewModel user, [FromQuery] string test)
        {
            if(!ModelState.IsValid ) 
            {
                return View(user);
            } 

            var check = _context.Exists(user.Email);
            if(!check) 
            {
                User ident_user= new User() { Email = user.Email};
                ident_user.SetPassword(user.Password);
                _context.Users.Add(ident_user);
                if(_context.SaveChanges() != 0)
                {
                    return RedirectToAction("login");
                }
                else
                {

                   ModelState.AddModelError("db", "Erreur dans la base de données");
                    return View();
                }
            } 
            else
            {
                ModelState.AddModelError(user.Email, "Un utilisateur existe déjà avec cet email");
                return View();
            }
        }
        [HttpGet]
        [Route("login")]
        public IActionResult Login() {
            return View();
        }

        [HttpPost]
        [Route("login")]
        [ValidateAntiForgeryToken]
        public  async Task<IActionResult> Login(LoginVModel model,string ReturnUrl) {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            string hpw = Tutorial.Models.User.HashPasword(model.Password);
            using(_context)
            {
                var user = _context.GetUser(new User(){Email= model.Email, Password= hpw });
                if(user != null)
                {
                   return await Connect(user,ReturnUrl);
                } 
                else
                {
                    ModelState.AddModelError(user.Email, "Email / Mot de passe incorrect");
                    return View();
                }
            }
        }
        public async Task<IActionResult> Connect(User user, string ReturnUrl)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Email),
                new Claim(ClaimTypes.Role, "Administrator"),
            };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperty = new AuthenticationProperties();

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity)
            );
            return Redirect(ReturnUrl == null ? "/pannel" : ReturnUrl);

        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Tutorial.Models;

namespace Tutorial.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Tutoriel";
}

<div class="text-center">
    <h1 class="display-4">Tutoriel</h1>
    <p>Proje d'initiation ASP.NET</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tutorial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="d-flex justify-content-end">
                <a asp-area="" asp-controller="Auth" asp-action="register">Inscription</a>
                <a asp-area="" asp-controller="Auth" asp-action="login">Se connecter</a>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tutorial</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Tutorial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>